### ISSUE TITLE
Crash not showing colors on windows

### ISSUE THREAD

**Issue by SnipeXY** [formerlybased/feather-engine#20] opened 2022-10-04 12:14 UTC
Crash does not show colors on windows

The following code
```
void Begin(){
    Crash("Test Crash");
}
``` 
produces the output
```
←[0;31mFATAL ERROR: ←[0mTest Crash. Engine will now shut down.
```
Instead of showing
```
FATAL ERROR: Test Crash. Engine will now shut down.
```
in which `FATAL ERROR: `  is in red

**Comment by Adamek-K** [comment] 2022-10-04 14:53
hey, yeah I am aware of this and am working on it. it is caused by crash trying to print an escape sequence to colour the characters, but that is not only platform specific but also terminal specific. I am working on getting a better solution for colouring the output of Crash()

**Comment by formerlybased** [comment] 2023-03-06 22:43
Error had to do with old debug system. Closing.

**Closed by formerlybased** 2023-03-06 22:43 UTC
Labels: bug
